default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: league_reports_development
  username: postgres
  password: password

test:
  <<: *default
  database: league_reports_test
  username: postgres
  password: password

production:
  <<: *default
  database: league_reports_production
  username: league_reports
  password: <%= ENV['LEAGUE_REPORTS_DATABASE_PASSWORD'] %>
